### ISSUE TITLE
Breaking on build

### ISSUE THREAD

**Issue by oneezy** [Snugug/vite-plugin-eleventy#3]
Running the developer server works fine `npm run dev` but building the project out fails `npm run build`. I thought it might have to do with the `index.html` file so I changed it to be `index.njk` and that didn't work.

---

**OS:** Windows 10
**Node Version:** v14.4.0

## Steps to reproduce

1. `npm init @vitejs/app`

2. `npm install vite-plugin-eleventy --save-dev`

3. `npm install`

4. create **vite.config.js** file
```javascript
// vite.config.js
const { eleventyPlugin } = require('vite-plugin-eleventy');

module.exports = {
  plugins: [eleventyPlugin()],
};
```
5. `npm run dev` (works)

6. `npm run build` (breaks)

**Comment by Snugug** [comment]
Thanks! Will look into this

**Comment by oneezy** [comment]
I did a fresh install following the same method described above and now it's not working on either `dev` or `build`.
![image](https://user-images.githubusercontent.com/7369575/124845735-ed878900-df5c-11eb-9c97-8df2a8a8be82.png)

**Comment by Snugug** [comment]
Well that's the new error so that's good! I'll go through the steps again and see what's up. It does look like it got through the compiling though, so that's an improvement.

**Comment by Snugug** [comment]
Ok, I think I know what the issue is and I think I fixed it (again). I wasn't normalizing paths for Windows machines correctly, so you were getting an error because my path and the root Vite supplies were, while the same path, represented differently (mine as a `win32` path, Vite as a normalized `posix` path). I've just pushed 0.0.9 which should _again_, solve this issue 😛
